version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../containers/flask/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db 
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ../containers/react/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    build:
        context: .
        dockerfile: ./containers/postgres/Dockerfile
    image: postgres:latest
    restart: always
    env_file:
      - .env
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

