version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: containers/flask/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env